# Adds more configs to default open api config
x-translator:
  component: KP
  team: [] # add teams
  biolink-version:
  infores:
x-trapi:
  version: 1.5.0
contact:
  email: "default@mail.org" # email
  name: "default-name" # name
  x-id: "default link" # link if available
  x-role: "default-role" # role
termsOfService: "" # link to terms of service
tags:
  - name: trapi
description: "" # Description for the whole spec
title: "" # title for the whole spec, overrides MMCQ_TITLE env value
servers:
  - description: Default server
    # This will be the base URL used when using openapi docs.
    # Note that to properly work, the URL host+port
    # should *NOT* have a trailing slash '/'
    url: http://localhost:8080
