version: '3.9'
services:
  api:
    build:
      context: .
    environment:
      SEMSIMIAN_PROTOCOL: "${SEMSIMIAN_PROTOCOL}"
      SEMSIMIAN_HOST: "${SEMSIMIAN_HOST}"
      SEMSIMIAN_PORT: "${SEMSIMIAN_PORT}"
      SEMSIMIAN_SEARCH: "${SEMSIMIAN_SEARCH}"
      WEB_HOST: "${WEB_HOST}"
      WEB_PORT: "${WEB_PORT}"
      MMCQ_SERVICE_ADDRESS: "${MMCQ_SERVICE_ADDRESS}"
      MMCQ_TITLE: "${MMCQ_TITLE}"
      MMCQ_VERSION: "${MMCQ_VERSION}"
      MODE: "${MODE}"
      OTEL_ENABLED: "${OTEL_ENABLED}"
      OTEL_USE_CONSOLE_EXPORTER: "${OTEL_USE_CONSOLE_EXPORTER}"
      OTEL_SERVICE_NAME: "${OTEL_SERVICE_NAME}"
      JAEGER_HOST: "${JAEGER_HOST}"
      JAEGER_PORT: "${JAEGER_PORT}"
    ports:
    - "8080:8080"
