services:

  mmcq:
    build:
      context: .
    environment:
      # defaults to access internal SemSimian Service
      SEMSIMIAN_SCHEME: "${SEMSIMIAN_SCHEME:-http}"
      SEMSIMIAN_HOST: "${SEMSIMIAN_HOST:-semsim}"
      SEMSIMIAN_PORT: "${SEMSIMIAN_PORT:-9999}"
      SEMSIMIAN_SEARCH: "${SEMSIMIAN_SEARCH}"
      WEB_HOST: "${WEB_HOST}"
      WEB_PORT: "${WEB_PORT}"
      MMCQ_SERVICE_ADDRESS: "${MMCQ_SERVICE_ADDRESS}"
      MMCQ_TITLE: "${MMCQ_TITLE}"
      MMCQ_VERSION: "${MMCQ_VERSION}"
      MODE: "${MODE}"
      OTEL_ENABLED: "${OTEL_ENABLED}"
      OTEL_USE_CONSOLE_EXPORTER: "${OTEL_USE_CONSOLE_EXPORTER}"
      OTEL_SERVICE_NAME: "${OTEL_SERVICE_NAME}"
      JAEGER_HOST: "${JAEGER_HOST}"
      JAEGER_PORT: "${JAEGER_PORT}"
    ports:
    - "8080:8080"

  semsim:
    image: us-central1-docker.pkg.dev/monarch-initiative/monarch-api/semsimian-server:${SEMSIMIAN_IMAGE_TAG:-latest}
    volumes:
      - "${HOST_DATA_DIR:-./data}:/data"
    environment:
      SEMSIM_SERVER_PORT: 9999
      PHENIO_PATH: "/data/phenio.db"
    ports:
    - "${SEMSIMIAN_PORT:-9999}:9999"
